# Generated by Django 5.2.9 on 2025-12-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieToActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'movietoactor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieToDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'movietodirector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieToGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'movietogenre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('actor_id', models.AutoField(primary_key=True, serialize=False)),
                ('actor_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'actors',
            },
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('director_id', models.AutoField(primary_key=True, serialize=False)),
                ('director_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'directors',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('runtime_min', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
